# Site settings
title: Zach Both
permalink: none
email: zach@zachboth.com
description: > # this means to ignore newlines until "baseurl:"
  The portfolio of filmmaker Zach Both. Available for contract work and creative collaborations.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zachboth.com" # the base hostname & protocol for your site
twitter_username: zachboth
github_username:  zachboth

# Build settings
markdown: kramdown

# Outputting
permalink: none
